### ISSUE TITLE
"chek" files

### ISSUE THREAD

**Issue by tjmahr** [LearningToTalk/NonWordTranscription#9]
Once there's a checking script, and if it outputs files with the pattern `NonWordRep_000L00FS2_XXsegm_YYchek.TextGrid`, the transcription script should be able to handle these files `chek` files. The script currently assumes that the textgrids are the manually checked `segm` files with the pattern `NonWordRep_000L00FS2_XXsegm.TextGrid`

**Comment by marybeckman** [comment]
The segmentation checker script outputs files with the same pattern as unchecked files, and the record of the segmenter's versus checker's initials is kept elsewhere.
